### ISSUE TITLE
Overview issue for beta release finalization

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1978]
As on the last sprint to finalize things it is difficult to have an overview of everything i propose to use this issue where specific changes can be collected.
For now the following points should be evaluated:

- [x] Hide "Add to custom dashboard button" @lubojr 
- [x] Add warning to scrollytelling when viewed on mobile device 
  - [x] review https://github.com/eurodatacube/eodash/pull/2009
  - [x] optionally check explore mode on mobile @lubojr
  - [x] mobile findings on https://github.com/eurodatacube/eodash/issues/1987
- [x] "Disable" datasets (i.e. Nowcasting, Hydro power, Micro hydropower, Urban trees) and buttons that are not available and add hover text, "Coming soon" , same for export function in energy transition
  - [x] add hover text "Coming soon" on disabled indicators, now just disabled item in list
- [x] Organize meeting with Patrick and Silvester to go over scrollystories, see also:
  - [x] https://github.com/eurodatacube/eodash/issues/1983
 - [x] https://github.com/eurodatacube/eodash/issues/1989 restructure indicators @lubojr 
 - [x] Fix ARI data in iframe mode (scrolly story)
 - [x] Total sum compute as a single number in flux chart, optionally as a draw your own polygon as well

Open tasks where inputs are needed:

- [x] Overall review of text for possible changes, organized by Patrick
- [x] Review of Scrollytelling content (also dedicated session for initial comments)
- [ ] Colormaps and data descriptors and description text for right side panel for all EO adapation datasets
- [x] Data desriptors missing for sustainable cities data
- [x] Finalize menu restructuring, communication here https://github.com/eurodatacube/eodash/issues/1839, awaiting inputs from Patrick and Mariangela
- [x] Should EO Adapt. services datasets be reorganized? Some added to Carbon accounting?
- [x] Patrick make sure https://github.com/eurodatacube/eodash/issues/1941 is finalized
- [ ] solar irradiance: 2 new datasets are expected, not clear if ingestion will be possible (on client same approach as height in wind energy)

**Comment by patrick-griffiths** [comment]
@lubojr and @silvester-pari 
I add a few smaller issues below

- [ ] Move all forestry related layers/variables to the "Carbon Accounting" domain, see screenshot below (data descriptors and legends will follow shortly) 
- [ ] Carbon accounting: rename CCI biomass to "Above Ground Biomass" and "Biomass" to "Forest Change" (not forest disturbance as indicated in Frank Martin email earlier)
- [ ] the NO2 layers (from S5P PAL) that are in the RACE dashboard, could we expose them as additional layer in the "mobility transition" domain? copy @DanGasb . @santilland indicated that this could be done by adjusting the config...
- [ ] Adjust the order of mobility transition tools/datasets: ARI, PM2.5, PM10, NO2, (RACE NO2), Innsbruck hotspot1, Innsbruck hotspot2, Dynamic human presence, dynamic human presence 
- [ ] solution to "grey out" (or similar) inactive tools, for example the micro hydropower, at hover indicate "coming soon!" 

![Image](https://user-images.githubusercontent.com/40148967/217773046-6270c415-08b1-491d-b2d3-9537744cff7e.png)

![Image](https://user-images.githubusercontent.com/40148967/217776945-9ba08c3d-bb55-4855-af5d-a76ab4d1b31d.png)

**Comment by mariangela-cataldo** [comment]
@lubojr please find here the icons for the Energy Transition subdomains
[GTIF-subdomains-energy-transition-icons.zip](https://github.com/eurodatacube/eodash/files/10698011/GTIF-subdomains-energy-transition-icons.zip)

**Comment by mariangela-cataldo** [comment]
@silvester-pari good morning! here's also the "Explore Tools" button/icon to be added just under the title+subtitle (i.e. under "Actionable information from Earth Observation to accelerate the Green Transition of society and economy"), linking directly to the Explore page 
![Explore tools icon](https://user-images.githubusercontent.com/115264145/218051348-8b8ad892-6ffe-4112-9ebe-920b5f751e22.png)

**Comment by patrick-griffiths** [comment]
@lubojr and @silvester-pari  I am adding a couple of bugs I spotted in the demo branch this morning: 

- [ ] The current one I would like to report, is that the Renewable  Wind Power density layers are not loading properly. The 200m layer loads by default without problems, but when selecting the 100 or 50m layers they do not display/load properly. Also switching back from e.g. 50m to 200m does not reload the 200m layer anymore. 

- [ ] The screenshot below, the 200m WPD layers shows no values (?) in eastern Austria/Burgenland, this is an area with low WPD values so likely an issue with the data scaling
 
- [ ] The filtering of the ruggedness index (windpower filter variable) is wrong currently: It should be set initially to a value of 1 (which includes all  values of WPD) and users can then move this value selection down towards 0 which increasingly masks out terrain influenced areas (0=maximum filtering). Currently the filtering starts by default at 0. 

- [ ]	I also noticed that ruggedness index info button does not display the data descriptor provided by DHI colleagues previously – I attach the relevant doc with the RIX data descriptor here for convenience 

![image](https://user-images.githubusercontent.com/40148967/218055598-54c0fd8b-1214-4f48-8af7-344272254a41.png)

[GTIF-energy-transition-data-descriptors (002).docx](https://github.com/eurodatacube/eodash/files/10705844/GTIF-energy-transition-data-descriptors.002.docx)

**Comment by mariangela-cataldo** [comment]
@silvester-pari may you please remove the "Set of Austria demonstrator domains" label from the narratives pages? now we have explicit titles and this is not necessary anymore (rather conflicting with the rest)?

**Comment by kegro** [comment]
@lubojr and @silvester-pari please replace logo

- [ ] can you change the DHI GRAS logo to DHI only. You can use the link below for the DHI logo.
https://grasdatastorage.blob.core.windows.net/images/DHI_Logo_rgb_Pos.svg

**Comment by mariangela-cataldo** [comment]
@silvester-pari here's a little update for the ENERGY PRESENT AND FUTURE IN EU AND AUSTRIA story: 

1. Two paragraphs describing the tools need to be added. You may find the text in Word format (last two rows) and an image of the expected layout (this shows only the part of the story on the teal background) in the jpg. Please check the layout also for the already existing text/embedded map.
2. May you please add the hyperlink to "National Energy and Climate Plans" in the first accordion content of the story? (https://ec.europa.eu/info/energy-climate-change-environment/implementation-eu-countries/energy-and-climate-governance-and-reporting/national-energy-and-climate-plans_en)
[ENERGY TRANSITION narrative contents final.docx](https://github.com/eurodatacube/eodash/files/10707562/ENERGY.TRANSITION.narrative.contents.final.docx)
![energyTransition_updatedLayout](https://user-images.githubusercontent.com/115264145/218097881-6774789d-ac73-4559-8b81-c36daf49e5f0.jpg)

**Comment by mariangela-cataldo** [comment]
@silvester-pari good morning! may we have the domain icons with names in the Mission Statement block (see image below), rather than only text?
![image](https://user-images.githubusercontent.com/115264145/218416060-b61accd8-bf3f-4bff-b5e7-d38a2e93e516.png)

**Comment by mariangela-cataldo** [comment]
> @silvester-pari good morning! may we have the domain icons with names in the Mission Statement block (see image below), rather than only text? ![image](https://user-images.githubusercontent.com/115264145/218416060-b61accd8-bf3f-4bff-b5e7-d38a2e93e516.png)

the icons should be triggering the side menu opening or, if not possible, inactive

**Comment by mariangela-cataldo** [comment]
> @silvester-pari here's a little update for the ENERGY PRESENT AND FUTURE IN EU AND AUSTRIA story:
> 
> 1. Two paragraphs describing the tools need to be added. You may find the text in Word format (last two rows) and an image of the expected layout (this shows only the part of the story on the teal background) in the jpg. Please check the layout also for the already existing text/embedded map.
> 2. May you please add the hyperlink to "National Energy and Climate Plans" in the first accordion content of the story? (https://ec.europa.eu/info/energy-climate-change-environment/implementation-eu-countries/energy-and-climate-governance-and-reporting/national-energy-and-climate-plans_en)
>    [ENERGY TRANSITION narrative contents final.docx](https://github.com/eurodatacube/eodash/files/10707562/ENERGY.TRANSITION.narrative.contents.final.docx)
>    ![energyTransition_updatedLayout](https://user-images.githubusercontent.com/115264145/218097881-6774789d-ac73-4559-8b81-c36daf49e5f0.jpg)

A couple of additional comments on the ENERGY PRESENT AND FUTURE IN EU AND AUSTRIA story:

1 - Would it be possible to have the first animation (GHG emissions) occupying a larger and more central space in the page? the short paragraph associated by scrolling might be visualised in smaller fonts

2 - Would it be possible to have the "round corners" around the visual elements consistently used in the page (i.e. also for the father-son video and for the windkraft embedded map)

3 - If not possible to avoid keeping a blank space for the accordion elements, how about transforming them into pop-ups? Otherwise the blank spaces might look like uploading errors...

**Comment by patrick-griffiths** [comment]
@lubojr please take note of the below

- [ ] Mobility data:: add units and colourmaps, see attachments here: https://github.com/eurodatacube/eodash/issues/1939

**Comment by mariangela-cataldo** [comment]
@lubojr @silvester-pari please find here attached the 2 icons to replace the ones used in the main menu for explore tools and narratives (in teal and white with transparent background)
![GTIF_dashboard_tools-10](https://user-images.githubusercontent.com/115264145/218421899-90e6a2b0-03c7-4402-a1f9-f6256d5e9287.png)
![GTIF_dashboard_tools-09](https://user-images.githubusercontent.com/115264145/218421905-00887c1c-e971-4a64-9a99-6fb5013bcdd9.png)
![GTIF_dashboard_tools-11](https://user-images.githubusercontent.com/115264145/218422044-75ec0175-c4e6-4dad-85eb-8c808e471a8c.png)
![GTIF_dashboard_tools-12](https://user-images.githubusercontent.com/115264145/218422049-6bf40992-7893-47bc-8609-a48a97cb0801.png)

**Comment by silvester-pari** [comment]
> @lubojr @silvester-pari please find here attached the 2 icons to replace the ones used in the main menu for explore tools and narratives (in teal and white with transparent background) ![GTIF_dashboard_tools-10](https://user-images.githubusercontent.com/115264145/218421899-90e6a2b0-03c7-4402-a1f9-f6256d5e9287.png) ![GTIF_dashboard_tools-09](https://user-images.githubusercontent.com/115264145/218421905-00887c1c-e971-4a64-9a99-6fb5013bcdd9.png) ![GTIF_dashboard_tools-11](https://user-images.githubusercontent.com/115264145/218422044-75ec0175-c4e6-4dad-85eb-8c808e471a8c.png) ![GTIF_dashboard_tools-12](https://user-images.githubusercontent.com/115264145/218422049-6bf40992-7893-47bc-8609-a48a97cb0801.png)

@mariangela-cataldo we had a look at these icons, but scaling them down to the current size of the sub menu items, the stroke is too thin to be visible.
Either we keep the current ones, or you provide ones with thicker stroke, or you provide us svg files so we can adjust the stroke accordingly. Thanks!

**Comment by mariangela-cataldo** [comment]
> > @lubojr @silvester-pari please find here attached the 2 icons to replace the ones used in the main menu for explore tools and narratives (in teal and white with transparent background)
> 
> @mariangela-cataldo we had a look at these icons, but scaling them down to the current size of the sub menu items, the stroke is too thin to be visible. Either we keep the current ones, or you provide ones with thicker stroke, or you provide us svg files so we can adjust the stroke accordingly. Thanks!
> 
> Please compare old versus new:
> 
> ![image](https://user-images.githubusercontent.com/26576876/218456362-3e27a604-483a-46ee-a743-fd416e988dc3.png) ![image](https://user-images.githubusercontent.com/26576876/218456370-79700dbc-2a7c-4f63-b2a8-28b9874ec96e.png)

Sure @silvester-pari, here come the svgs, please let me know if they are fine now

![Explorer tool icon-explorer](https://user-images.githubusercontent.com/115264145/218475127-29c26f05-86ad-45f1-b91b-b49636d51a1b.svg)
![Explorer tool icon-stories](https://user-images.githubusercontent.com/115264145/218475132-51cf4a02-3251-4713-a2c8-a161bf6acf98.svg)

**Comment by patrick-griffiths** [comment]
@lubojr @silvester-pari here the updated disclaimer: 

GTIF - Beta release
You are currently viewing a beta release of the Green Transition Information Factory (GTIF) demonstrator for Austria. This release features an initial set of tools and content. There is much more in development and coming! Please also note that this version is not yet optimised for mobile view and there might be some issues with certain browsers. For now, we invite you to explore the GTIF environment and get engaged to support our transition to a sustainable future. Feel free to provide feedback, wished and recommendations using the feedback form or via [gtif@esa.int](mailto:gtif@esa.int).

**Comment by lubojr** [comment]
Tasks from today's meeting:

- [ ] Check ruggedness filter on deployed version, locally works
- [ ] Replace logo of ZAMG with new name
- [ ] PM2.5 or PM10 or ARI usage?, add redundancy (queryParameters x 3)
- [ ] Update navigationDescription for AQB
- [ ] Story: hotspot analysis overlapping text
- [ ] Story: “For each half hour”, show on previous image - mobility transition
- [ ] Story: Sustainable cities -> first two text blocks should be above the video, removing title was correct
- [ ] Stories: Problem on safari with color of the super tall image (she sees it grey)
- [ ] Stories: Browsers - safari has general issues -> 2nd run of testing
- [ ] Stories: For chrome, explore tools look okay, but her scrollytelling is completely broken, on 125% text size ?

**Comment by mariangela-cataldo** [comment]
@silvester-pari in Home Page: can you please add the same effect you have on hover of the domain icons to the new explore tools icon, so that it's clearer it is an active one?

**Comment by lubojr** [comment]
@patrick-griffiths 

> * Check ruggedness filter on deployed version, locally works

This works for me also on the deployed version, so I can not replicate it. If I may ask, what was the exact workflow in the app that made it not functional for you?

**Comment by patrick-griffiths** [comment]
@lubojr @silvester-pari 
Energy explore tools, solar energy --> please enable the "exclude protected areas" function also here
(it was active before but then disappeared - this is relevant for wind and solar)..
Thanks!

**Comment by patrick-griffiths** [comment]
@lubojr right now the Ruggedness index in the https://gtif-demo.eox.at/ branch worked fine ...

**Comment by patrick-griffiths** [comment]
@lubojr thx for the feedback.. 
after the hard reload and a couple of tests it seems to consistently work..

**Comment by DanGasb** [comment]
Mobility transition scrollytelling:
- First block of text is not formatted (white space, different size of the text), see figure 1
![Figure1](https://user-images.githubusercontent.com/117925117/218688899-dd7e9285-2289-4b20-9a75-e669e0a219b9.PNG)
-  After the ARI block there is only a caption, figures are missing
![Figure2](https://user-images.githubusercontent.com/117925117/218689212-fb9ef145-dfec-4532-93f8-e263e13b614c.PNG)
- The 15days NO2 maps are not yet updated, there are still maps with fake hot-spots. Remove the variable from the menu if the new data will not uploaded before the release.

Thanks,
Daniele

**Comment by lubojr** [comment]
> * First block of text is not formatted (white space, different size of the text), see figure 1

@DanGasb We did not manage to make the fixes before the release due to lack of time, we will push fixes for these first two items after a few hours to not disrupt the demo.

What do you mean by item 3, could you please elaborate more.

**Comment by DanGasb** [comment]
Yesterday SISTEMA uploaded in S3 bucket new NO2 maps with different quality flag thresholds (you were not in cc, I forwarded the mail to you). 
The maps now on line refer to their previous (wrong) attempt and provide incorrect message to the user.

**Comment by lubojr** [comment]
NO2 maps have now been updated, I believe all other issues already have their own dedicated issue, so I would close this encompassing issue.
