### ISSUE TITLE
Review matomo tracking for GTIF

### ISSUE THREAD

**Issue by Schpidi** [eurodatacube/eodash#2068]
- [ ] add gtif segment in eodash website matomo configuration
- [ ] add weekly report sent to slack
- [ ] review that activating explore tools and scrollytelling is properly tracked in order to see which stories are looked at
