### ISSUE TITLE
May V1.0 release bugs tracking

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#2203]
here we can keep track of smaller issues that we notice in preparation of the V1.0 release end of May

**Comment by patrick-griffiths** [comment]
- [ ] hydro reservoir monitoring - the S1 SAR imagery creates strange artifacts -  see below, this is certainly not present in the source imagery @lubojr @santilland 

![Image](https://github.com/eurodatacube/eodash/assets/40148967/4143d7dd-4a75-4996-9bb5-5be2e3888b1a)

**Comment by lubojr** [comment]
@patrick-griffiths We were using a `radiometric terrain corrected` as default visualisation of S1 from sentinelhub - please have a look at https://sentinelshare.page.link/cMqs 
There are multiple other available options, please pick one which you think would support the cases the best and we shall use that particular evalscript in our layer definition. Thank you.

**Comment by patrick-griffiths** [comment]
thanks @lubojr - noted that this comes directly out of SH... 
will discuss with some SAR experts, it does look somehow exaggerated

**Comment by aapopescu** [comment]
for visualisation please consider using the orthorecitified or gamma0 layers instead of the RTC

**Comment by AlessandroScremin** [comment]
@aapopescu @lubojr 
the layer selectd was already gamma 0, not th RTC...but ortorectification enabled with default DEM. so what I can do is to disable  the orthoretification...

@lubo try now I changed the E8_Sentinel1 with no orthorectification.

**Comment by AlessandroScremin** [comment]
![image](https://github.com/eurodatacube/eodash/assets/65602207/686bf069-c295-4320-992e-49a9adfff448)

**Comment by lubojr** [comment]
@AlessandroScremin Thank you for the reconfiguration.

We have looked over several high altitude lakes and indeed the rendering artifacts are now gone - they were caused by the DEM orthorectification. But the DEM orthorectification also had a positive influence on "georeferencing of the images" in high altitude areas (where most of our tracked reservoirs are).

See for example 
![image](https://github.com/eurodatacube/eodash/assets/19269667/f91e2dd5-e11c-4eba-be13-5908a9b6176b) and 
![image](https://github.com/eurodatacube/eodash/assets/19269667/53fe5cea-78be-453e-8294-e0597cfcb2da)

taken from https://gtif.esa.int/explore?poi=573-REP4_1

The influence of the positional shift varies in magnitude and direction for different scenes/dates.

@patrick-griffiths Is the current S1 visualisation sufficient?

**Comment by AlessandroScremin** [comment]
@lubojr 
As it was the same layer used for E8 indicator in race...could you please check if it is affeccted?
I looked at one of the finished good inventory and see only the timeseries (no sar image)...I don't remember if it was still used there...if not then we can keep the layer changes

**Comment by lubojr** [comment]
@AlessandroScremin We use S1 layer (E8_SENTINEL1) in following indicators: 
https://race.esa.int/?poi=UK12-E12b - looks good
https://race.esa.int/?poi=ES7-E1 - archived, looks good
https://race.esa.int/?poi=PL5-E5 - archived, some dates missing, but looking good

From my point of view, I'd say you can leave that changed for race as well.

**Comment by AlessandroScremin** [comment]
@lubojr 
Checked...good...perfect. So let the layer in this way!!

Thanks

**Comment by patrick-griffiths** [comment]
@lubojr sorry for missing the above discussion earlier.
I agree with @aapopescu suggestion to go for (VH decibel) gamma0.
It looks best for these visualization purposes

Example here: 
https://apps.sentinel-hub.com/eo-browser/?zoom=14&lat=47.23639&lng=10.87758&themeId=DEFAULT-THEME&visualizationUrl=https%3A%2F%2Fservices.sentinel-hub.com%2Fogc%2Fwms%2Ff2068f4f-3c75-42cf-84a1-42948340a846&datasetId=S1_AWS_IW_VVVH&fromTime=2022-12-30T00%3A00%3A00.000Z&toTime=2022-12-30T23%3A59%3A59.999Z&layerId=IW-DV-VH-DECIBEL-GAMMA0&demSource3D=%22MAPZEN%22

![image](https://github.com/eurodatacube/eodash/assets/40148967/1fc2d201-0bdc-448e-a804-c005acaa2049)

**Comment by santilland** [comment]
@patrick-griffiths filter to constraint wording has been done, currently on staging environment will be included in next demonstrator deployment

**Comment by patrick-griffiths** [comment]
@santilland @lubojr 

Energy > Solar --> Currently the constraint for the Solar irradiance itself only affects the stretch of values, it does not limit the irradiance layers as expected (compare to what happens with wind): 

https://gtif.esa.int/explore?x=1742987.39595&y=5965561.33671&z=9.15831&clusterOpen=5&poi=Austria-REP2

![Image](https://github.com/eurodatacube/eodash/assets/40148967/8edeeeae-f7f8-4209-b22d-664b82e3fff8)

**Comment by patrick-griffiths** [comment]
Custom Dashboard button shown purposefully (current demo branch)? 
If so, it should be renames to "create scrollytelling content"

![Image](https://github.com/eurodatacube/eodash/assets/40148967/30dc27c2-f1f3-4f6f-8ac6-8588b137d9c6)

**Comment by santilland** [comment]
> Custom Dashboard button shown purposefully (current demo branch)? If so, it should be renamed to "create scrollytelling content"
The custom dashboard button is only visible for someone who has opened a custom dashboard edit link, this should only be the case for people adviced on how to creat this content and not for the general public

**Comment by patrick-griffiths** [comment]
- [ ] Forest explorer - zoom to extent of data by default (Styria?)
- [ ] Forest disturbance - possibility to activate statistics by click on admin unit (similar to green/solar roofs)? screenshot below
- [ ] Energy: wind site suitability: the "distance to settlement" based on cadastral data does not work as expected, it blinds out everything at 100% when moving the slider up to e.g. 10% (second screenshot below)
- [ ] Energy: basemaps, rename "wind power" to "Wind Power Density && rename "census track" to "admin units"
- [ ] Energy: Hydro: by default, activate the Geoland Basemap Gelaende instead of the orthophotos 

![Image](https://github.com/eurodatacube/eodash/assets/40148967/145f78e2-6c3c-448e-ab4f-5df07d325b82)

![Image](https://github.com/eurodatacube/eodash/assets/40148967/f89f3125-0b64-4f28-b039-e20be9561a9a)

**Comment by patrick-griffiths** [comment]
@lubojr @santilland 

- [ ] energy > solar: the constraint slider for Global Horizontal Irradiation currently adjusts the strech, while it should lead to a filtering of value ranges (similar to wind WPD)
- [ ] energy > solar: also the stretch of the data value ranges does not allow seeing meaningful differences, see screenshot below. @kegro did you guys provide some optimized stretch values? 



![Image](https://github.com/eurodatacube/eodash/assets/40148967/9f206491-edf7-42ff-b2d7-05902ac1b7a0)

**Comment by patrick-griffiths** [comment]
@santilland ok but this circumvents / breaks the purpose of the tool, which is to preform site suitability assessment, where the first step is to constrain (filter) the value range of the irradiance layers (analogue to what we do for wind). 

If you need to provide dynamic stretch, it needs to be explicitly labeled as that, and we still need the constraint slider for filtering the values!!

**Comment by santilland** [comment]
> @santilland ok but this circumvents / breaks the purpose of the tool, which is to preform site suitability assessment, where the first step is to constrain (filter) the value range of the irradiance layers (analogue to what we do for wind).
> 
> If you need to provide dynamic stretch, it needs to be explicitly labeled as that, and we still need the constraint slider for filtering the values!!

ok, we should be able to do the stretch and filter out all values above and below the current range, i will have a look

**Comment by kegro** [comment]
> @kegro did you guys provide some optimized stretch values?

It is quite difficult to display the annual and seasonal layers with the same stretch and at the same time show the variation within each layer. A stratch between 0.5 and 6 is probably best for this. However, to dsiplay them to show the variation within each layers then different stretches are needed. @santilland we can give you some guidance here if you like?

**Comment by santilland** [comment]
@patrick-griffiths @kegro on following branch is an option how stretch and filtering would be done at the same time, i think this is the best approach we can do currently, we can consider a more elaborate solution for the future.
https://gtif-testing.eox.at/gtif_solar_filter/

**Comment by patrick-griffiths** [comment]
@kegro could you give this a try and let us know>?

**Comment by kegro** [comment]
@santilland @patrick-griffiths I think this works. It doesn't take long to learn that the stretch and filtering is done with the same slider, so from I user I think it is OK. A bit hard to keep track of what values relates to which color, but the value range is quite explicit on the slider. All the other filtering options seem to work fine too.

**Comment by slumnitz** [comment]
@santilland and @lubojr we also would need to remove the urban tree tab from the user interface as this data will not be made available soon. (fit @patrick-griffiths )

**Comment by slumnitz** [comment]
@santilland and @lubojr the sustainable cities datasets load very slow. Are there any possible speedups that could be implemented in future or soon? (@patrick-griffiths )

**Comment by slumnitz** [comment]
> @slumnitz Currently the colors are done followingly:
> 
> In the map each selected ZSP feature uses a new color from this list https://github.com/eurodatacube/eodash/blob/gtif_staging/app/src/appConfig.js#L315-L318 based on the index of the feature in the list
> 
> On the chart, the colors are aggregated per gemeinde (each gemeinde has a new color also from this list), so if you select Graz and some other Gemeinde, then respective ZSP from the other Gemeinde are also drawn by the second color of the array.
> 
> Exception to that are all the selected ZSP (which triggered the original gemeinde search) - those are red.
> 
> Nonselected ZSP can be changed to grey, but then we lose comparison between 2 gemeinde.
> 
> Please advise how to proceed.

@lubojr thank you for the explanation! I understand, for the release now, to not confuse the user I would:
A) Keep the selection on the map to one colour the same one used for highlighting the plots in the Gemein, 
B) and make the outline of the selected Zeahlsprengel more dominant, i.e. 2x original ZSP. You are also welcome to test different approaches, but currently the selected ZSP is not really visible on a MAC screen.
C) currently selected ZSP in different Gemeinde have the same colour can they be made a different colour to distinguish ZSP selected in Gemeinde A from ZSP selected in Gemeinde B?

**Comment by slumnitz** [comment]
@lubojr perhaps another way could be to additionally to the more dominant outline to make the alpha not white colouring but coloured colouring?

**Comment by patrick-griffiths** [comment]
@santilland @lubojr 

This below should replace the beta version disclaimer that is currently shown when the explore tools are opened: 



Welcome to the V1.0 release of the Green Transition Information Factory – Demonstrator for Austria! 
**What’s new**:  

**- Energy Transition:**
- Hydroelectric reservoir monitoring 
- ML-based wind turbine detection
- Energy planning: Seasonal solar irradiation, new constraining variables
**- Sustainable cities:** 
- Full country green & solar roofs analyses
**- Carbon accounting:** 
- 20m forest biomass products
- Country wide disturbance mapping & change attribution
**- Mobility transition:** 
- Correlation explorer: Air quality & human mobility
- Sentinel-2-based truck detection indicator
**- EO adaptation services:**
- Expanded heat explorer
- Snow depth & snow water equivalent products
- Alpine Drought Explorer elements
**- New and Improved scrollytelling narratives**
- UI/UX enhancements: 
- Compare regions
- Export regions as geoJson
- Create report

formatted basically as below

![Image](https://github.com/eurodatacube/eodash/assets/40148967/7d1e1c21-006b-4b11-add5-b63a2edc84b5)

**Comment by patrick-griffiths** [comment]
@santilland @lubojr 

For the mobility transition: 

- [ ] "human mobility patters" remove this for now (we will reactivate it once the latest data and full time series is integrated)
- [ ] "dynamic human presence" remove this for now (we will reactivate it once the latest data and full time series is integrated)
- [ ] rename "aggragated mobility data" to "correlation explorer: AQ-mobility" - we will add an updated disclaimer later
- [ ] truck detection should appear last in the list

**Comment by patrick-griffiths** [comment]
@santilland @lubojr 
for the Alpine Drought Explorer: 

- [ ] add the icon below to the ADO consortium
- [ ] please see attached 4 data descriptor tables to be exposed behind the info button (and potentially replace part of this for the right panel description, so it does not appear blank)
- [ ] update the title to " Alpine Drought Observatory" rather than exploratory

![Image](https://github.com/eurodatacube/eodash/assets/40148967/b5ea1bb3-a60d-4720-94cc-2e65ec9a6fae)

[Standardised Precipitation Index_12.docx](https://github.com/eurodatacube/eodash/files/11601435/Standardised.Precipitation.Index_12.docx)
[Standardisied Precipitation-Evapotranspiration Index_1.docx](https://github.com/eurodatacube/eodash/files/11601436/Standardisied.Precipitation-Evapotranspiration.Index_1.docx)
[Standardisied Precipitation-Evapotranspiration Index_12.docx](https://github.com/eurodatacube/eodash/files/11601434/Standardisied.Precipitation-Evapotranspiration.Index_12.docx)
[Standardised Precipitation Index_1.docx](https://github.com/eurodatacube/eodash/files/11601437/Standardised.Precipitation.Index_1.docx)

**Comment by santilland** [comment]
@patrick-griffiths latest state on staging deployment:
https://gtif-staging.eox.at/
This has the new welcome message, the aggregated mobility data were some fixes needed to be done, as well as the new daily aggregated mobility pattern.
I will then continue on the rest of points and write updates here

**Comment by patrick-griffiths** [comment]
@santilland @lubojr 
Not sure if I have listed these small changes anywhere: 
- [ ] Energy: remove nowcasting, keep microhydro greyed out for now
- [ ] Energy: solar: be default start the sliders at min -max range (instead of a preset stretch)
- [ ] forest explorer: zoom to styria by default
- [ ] Energ: turbine detection: integrate data descriptors (came via email)

**Comment by patrick-griffiths** [comment]
> @patrick-griffiths latest state on staging deployment: https://gtif-staging.eox.at/ This has the new welcome message, the aggregated mobility data were some fixes needed to be done, as well as the new daily aggregated mobility pattern. I will then continue on the rest of points and write updates here

Lots of things look very good, thanks!

- [ ] disclaimer: linebreak before "What's new" to move it into next line
- [ ] mobility: reorder elements: ARI, PM10, PM2.5, NO2 Correlation Explorer, Innsbruck hot spot, Innsbruck hotspot2, truck detection
- [ ] mobility: remove/deactivate "dynamic human presence", dynamic human presence - we have to evaluate this full time series first a bit more (its the first time we see it) keep it in staging but do nor merge it into demo; 
- [ ] carbon accounting, disturbances: remove zoom highlight Styria
- [ ] mobility: correlation explorer: update disclaimer on right side with below text

_In order to better understand how people's movement and mobility affects air quality parameters, this tool allows exploring correlations between Sentinel-5P measurements and human mobility data. 

For this both data sources were aggregated to the same spatial grid. For the air quality parameters daily Sentinel-5P Tropomi observations were used. For the mobility data, only observations that preceded the S5P observation by four hours was considered. Four hours is the typical time that NO2 can remain in the atmosphere and thus be detected.

The tool supports users in exploring temporal spatial patterns between both variables and identify potential correlations. The mobility data only captures around 22% of the population and is then calibrated with population presence and density. Thus, it is one form of capturing people’s movement but likely not the most suitable. Consequently, estimates provided for Number of Trajectories, Congestion Index, Speed, Motorized Count, and Motorized Share may not be reflecting the reality of mobility on the ground with very high precision. Nevertheless, this tool is a first attempt in allowing users to explore air quality parameters and mobility statistics interactively._

**Comment by lubojr** [comment]
> @lubojr I would also recommend to make the dot's in the scatterplot a slight alpha=0.7 (slight transparency) so that all dot's are visible even if they overlap.

I have added alpha to the scatterplot items, so the items are a bit more visible

I have also updated the selection logic on the map, so that the currently selected ZSP now do not have a special color (it is not straightforward to match the selected ZSP to the original Gemeinde on the map) but instead the selected ZSP have an increased stroke width, so it is more clear on the map which are selected. The user can then hover on the map to see which one is which. The confusion on different color wrt. the map and the chart should now be gone, as map on SOL1 will now have only 1 color of the ZSP features - dark green.

**Comment by Antony-Delavois** [comment]
> * [x]  mobility: correlation explorer: update disclaimer on right side with below text
> 

A quick update on the disclaimer:

This tool allows exploring potential correlations between Sentinel-5P/TROPOMI measurements and human mobility data, with the objective to better understand how people's movement and mobility affects air quality parameters. 

For this purpose, both data sources were aggregated to the same spatial grid. For the air quality parameters daily S-5P observations were used. For the mobility data, only observations that preceded the S-5P observation by four hours was considered. Four hours is the typical time that NO2 can remain in the atmosphere and thus be detected.

The mobility data only captures around 22% of the population and is then calibrated with population presence and density. Thus, it is one form of capturing people’s movement but likely not the most suitable. Consequently, estimates provided for Number of Trajectories, Congestion Index, Speed, Motorized Count, and Motorized Share may not be reflecting the reality of mobility on the ground with very high precision. 

Being a demonstrator on how to integrate and interactively compare air quality parameters versus mobility statistics, further validation is needed to be able to allow meaningful conclusions.

**Comment by lubojr** [comment]
> * mobility: remove/deactivate "dynamic human presence", dynamic human presence - we have to evaluate this full time series first a bit more (its the first time we see it) keep it in staging but do nor merge it into demo;

 @patrick-griffiths Just for double checking, you meant to disable: `Human Mobility Patterns` and `Dynamic human presence` or just `dynamic human presence`?

**Comment by santilland** [comment]
> mobility: remove/deactivate "dynamic human presence", dynamic human presence - we have to evaluate this full time series first a bit more (its the first time we see it) keep it in staging but do nor merge it into demo;

hello @patrick-griffiths about the mobility data, we really put quite some effort in being able to load the data yesterday, i think with the new daily aggregated data at least for human presence it is quite a nice thing to show, at least the time series.
Having the disclaimer makes clear that the data needs to be consumed taken possible issue into account.
![image](https://github.com/eurodatacube/eodash/assets/4036819/72c05677-8678-4b99-8213-c17cc064b1df)

I would propose to reactivate them.

**Comment by patrick-griffiths** [comment]
> hink with the new daily aggregated data at least for human presence it is quite a nice thing to show, at least the time series.

okay @santilland lets keep them in, 
I was not aware of the time series functionality that is now enabled, nice indeed!

**Comment by patrick-griffiths** [comment]
@lubojr @santilland - a few small fixes: 
- [ ] Energy > Turbines > deactivate "power open infrastructure map" by default
- [ ] Energy > Turbines > S2 overlay: adjust the stretch (see below, assuming this is dynamically determined) a bit so the image appear brighter and with more contrast. as this is late seasonal imagery (e.g. november, february) the sun is lower and hence the scene darker.... 
- [ ] Energy > Turbines > selecting individual bounding boxes doe snot seem to work anymore, making it difficult to understand when a detection is selected (and overlay activated)
- [ ] mobility > Human Mobility Patterns > (please reactivate - see above) could the width of the street/trajectories be increased by 20% at closer zoom levels? 
- [ ] mobility > Human Mobility Patterns > is there a dark base map we could use to enhance the contrast and make it visually more appealing

![Image](https://github.com/eurodatacube/eodash/assets/40148967/b1c950e6-32a4-45a8-8643-11de42f28903)

**Comment by aljacob** [comment]
on the layer selection there is still the wrong label of alpine drought exploratory-> should be Alpine Drought Observatory as well
![image](https://github.com/eurodatacube/eodash/assets/7644251/1f3bf298-a288-4045-ad00-4050172bc663)

**Comment by Antony-Delavois** [comment]
> 

updated with more info on how mobility data is processed

**Comment by Antony-Delavois** [comment]
Mobility disclaimer updated with more info on how mobility dataset is processed

**Comment by patrick-griffiths** [comment]
@santilland @Schpidi

When people post the GTIF URL the RACE preview is down. Very confusing. Please remove this! 



[]()

**Comment by santilland** [comment]
@patrick-griffiths is it a specific url?
the main gtif url expands with gtif information, e.g.:
![image](https://github.com/eurodatacube/eodash/assets/4036819/6d7ff8ec-8671-490d-b44b-13cfb15e5479)

**Comment by patrick-griffiths** [comment]
> @patrick-griffiths is it a specific url?
> the main gtif url expands with gtif information, e.g.:
> ![image](https://github.com/eurodatacube/eodash/assets/4036819/6d7ff8ec-8671-490d-b44b-13cfb15e5479)
> 

LinkedIn post URL is above, I only see the general links to gtif.. Strange

**Comment by silvester-pari** [comment]
Hello @patrick-griffiths , thanks for spotting this, this was actually a cache on the side of LinkedIn - cache has been cleared, it now looks like this:

![image](https://github.com/eurodatacube/eodash/assets/26576876/97ab2f3b-9d4e-43d2-9000-6e3c324b47e3)

**Comment by santilland** [comment]
> > @patrick-griffiths is it a specific url?
> > the main gtif url expands with gtif information, e.g.:
> > ![image](https://user-images.githubusercontent.com/4036819/242392337-6d7ff8ec-8671-490d-b44b-13cfb15e5479.png)
> 
> LinkedIn post URL is above, I only see the general links to gtif.. Strange

@patrick-griffiths  the expanded image was cached in linkedin, we updated it shows correctly now:
![image](https://github.com/eurodatacube/eodash/assets/4036819/f1a9bfef-ab2d-4104-9b3b-e47d4cf754f4)
