### ISSUE TITLE
UI Panels - styling checklist

### ISSUE THREAD

**Issue by silvester-pari** [eurodatacube/eodash#2347]
Connected to https://github.com/eurodatacube/eodash/issues/2331

# Desktop

- [x] remove bottom gap under UI panels (if left or right adds up to 100%, it should occupy full height of the map window)
- [x] remove "hidden story display div" hack from data panel, e.g. mutate the store directly on indicator change, not inside computed property
- [x] narrative mode: remove unnecessary scrolling from narrative list
- [x] tools mode: rename "Filters" UI panel to "Domains & Tools"
- [x] either move map buttons to some other location or introduce padding on the right-hand UI panels - currently overlaying each other
- [x] remove map layers button (top right) as it is replaced by layers UI panel
- [x] tools mode: fix double scrollbar in Domains & Tools UI panel
- [x] narrative mode: hide "tools" in itemfilter (only make domain selectable)
- [ ] tools mode: hide "empty" UI panels, e.g. if no content in Analysis panel, don't display Analysis UI panel at all, same for Information panel
- [x] fix map legend overlaying panels, e.g. moving truck detections
- [x] fix map control buttons positioning (zoom, drawing buttons, etc. - e.g. moving truck detections), currently are not vertically aligned

# Mobile

- [x] remove gap between UI panel buttons (mobile) and UI panels; make distance calculation dynamic to work for both one-line and two-line text
- [x] fix narrative/tool switch positioning (currently overflowing / cut off to the right)
- [x] fix UI panel tabs border radius
- [x] remove padding & margin around UI panel tabs/container so tabs feel like "extension of footer"
- [x] highlight currently active tab (background color)
- [x] move map attribution button above UI panel tabs
- [x] make currently active tab closeable by introducing a close button in the top right
- [x] make active full-screen UI panel scrollable (e.g. if the story is long, it gets cut off and is not scrollable)

**Comment by lubojr** [comment]
Some points I have observed now only necessary styling:

- [ ] add tooltip on hover to the 2 buttons for switching between Narratives and Explore tools 
![image](https://github.com/eurodatacube/eodash/assets/19269667/e6e90e5a-25e5-4af9-be06-582ecfd9eda6)
- [ ] On other instances than GTIF, it is possible to "embed" the whole map as an Iframe, which is triggered by another button in the bottom right of the map. Coordinates of mouse (latlon) cover it. To try it out, use the eodash.localhost instance. update the styling of the mouse position so they are not covered
![image](https://github.com/eurodatacube/eodash/assets/19269667/f31614f2-0b1a-4ca1-b209-e9d448bcb6d2)
- [ ] update the header in the ItemFilter from Tools to Narratives but only in case the "narratives mode" is enabled 
![image](https://github.com/eurodatacube/eodash/assets/19269667/b7e14129-ada8-4820-8951-fa52254e71f0)
- [ ] remove the large margin between end of Domains and start of Tools in ItemFilter and 
- [ ] make the mouse position (latlon) disappear when mouse is not pointing to map (remove the mini div without text completely)
- [ ] reduce free space between domains and tools and domains

**Comment by lubojr** [comment]
A follow list of TODOS:

- [ ] Move Legend to Layers panel
- [ ] Layer Freeze - Move it under a button to Analysis Panel
- [ ] Frozen layer moved from Data Group into the top level
- [ ] Bring back the breadcrumbs of the domains
- [ ] Add “visusalisation” to layer group names (background + overlays)
- [ ] Move wind turbine detections to the overlays from REP1
- [ ] Switch between narrative/tools more prominent + larger (white background instead of grey)
- [ ] Test out stories + scrolly!
- [ ] Fix the timeslider is hidden when times.length = 1
- [ ] Add unit of measurement on titles?

**Comment by lubojr** [comment]
Style override for making the text of stacinfo not bold and generally smaller is pending a merge and release of https://github.com/EOX-A/EOxElements/pull/390

**Comment by lubojr** [comment]
Style override for making the information panel text smaller applied.
