### ISSUE TITLE
BIDs 2023 checklist

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#2351]
- [x] Add reference to new notebook in official story of Wildfires -> https://bids2023-nbviewer.hub.eox.at/localfile/bids2023/notebooks/Fire_impact_analysis.ipynb?format=html_plain
- [x] copy updated VEDA NTB to .shared and try running it
- [x] Update reference to the new notebook for VEDA access
- [x] Setup eodash-catalog branch with "newly" added N12 test dataset into a trilateral catalog
- [x] Update markdown of GCOM-W sea ice N12 indicator
- [x] Integrate https://github.com/eurodatacube/eodash/issues/2312 both into old and new system

cc @aapopescu
